# Generated by Django 5.0.3 on 2026-05-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="image_url",
            field=models.URLField(
                blank=True, help_text="Unsplash or any direct image URL", null=True
            ),
        ),
    ]
