# Generated by Django 5.0.3 on 2026-05-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0002_add_image_url_to_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="image_url",
            field=models.URLField(
                blank=True,
                help_text="Direct URL to a real food image (e.g., from Unsplash)",
                max_length=500,
                null=True,
            ),
        ),
    ]
